### ISSUE TITLE
Warning: filectime() [<a href='function.filectime'>function.filectime</a>]: stat failed for 2013-07-28 20.27.35.jpg in C:\wamp\www\gallerysite\index.php on line 8

### ISSUE THREAD

**Issue by devenbhooshan** [hughrawlinson/theplacesitakemylaptop.me#2]
This time i am no bot.  :p

**Comment by hughrawlinson** [comment]
Stat failed? (sorry, I must've missed/forgot about this).

**Comment by hughrawlinson** [comment]
[This stackoverflow question may have helped](http://stackoverflow.com/questions/7017762/filectime-function-filectime-stat-failed-for). I've only tried this on Ubuntu, and I turned off this project ages ago.
